export const institute = [
  {
    id: 11,
    instutionType: "university",
    name: "FED-LAFIA",
    fullname: "Federal University, Lafia",
    institutionSummary: "",
    pmb: "P.M.B. 146, Lafia, Nasarawa State.",
    address: "",
    tel: "",
    state: "",
    universityType: "Federal University",
    entryReq: [
      "Federal University, Lafia requires all candidates applying for admission into any of its courses to possess at least Five (5) “O” Level credit passes in not more than two sittings including English Language and Mathematics.",
      "Federal University, Lafia does not accept awaiting results candidates for all its programmes (so awaiting results candidates need not apply to the University).",
    ],
    directEntry: [
      "Federal University, Lafia does not currently accept Direct Entry candidates for all its programmes (so Direct Entry candidates need not apply to the University).",
    ],
  },
  {
    instutionType: "polytechnic",
    name: "AFIT",
    fullname: "Air Force Institute of Technology, Nigerian Air Force",
    institutionSummary: "",
    email: "E-mail: registrar@afit.edu.ng Web Site: www.afit.edu.ng",
    pmb: "P.M.B. 2104 Kaduna Tel: 07029306014",
    address: "",
    tel: "",
    state: "",
  },
  {
    name: "ADEYEMI",
    fullname: "Adeyemi College of Education,",
    affilatedUniversities: "Obafemi AwolowoUniversity, Ile-Ife, Osun State",
    pmb: "P.M.B 520, Ondo. Tel: 034-610050",
  },
  {
    instutionType: "other-degrees",
    name: "CAILS",
    fullname: "College of Arabic and Islamic",
    affilatedUniversities: "Bayero University, KanoLegal Studies, Ilorin",
  },
  {
    instutionType: "innovation-centers",
    name: "AFRIHUB",
    fullname: "Afrihub ICT Institute, Abuja",
    institutionSummary: "",
    email: "E-mail: ese.egerega@afrihub.com",
    pmb: "",
    address: "AP Plaza, Ademola Adekunbo Crescent, Wuse II, Abuja, FCT .",
    tel: "",
    state: "",
  },
];

export const primary = [
  {
    id: 0,
    course: "ACCOUNTANCY / ACCOUNTING",
    schools: "AAUA",
    ssce: "Five SSCE credit passes including English Language, Mathematics, Economics and any other two relevant subjects. For NBC holders, the other two relevant subjectscould be from any of Accounting, Principles of Accounts, Commerce, Office Practice and Secretarial Duties.",
    utme: "Mathematics, Economics, any Social Science subject.",
    years: 4,
    degree: "Bachelor of Administration",
    degreeAbbr: "B.A. (Hons)",
    mode: "Fulltime",
    faculty: "Administration",
    courseSummary: "",
    institutionType: "University",
    image: "/accountancy/accounting-aaua",
    isFeatured: true,
  },
  {
    id: 1,
    course: "ACCOUNTANCY",
    schools: "ABIAPOLY",
    ssce: "English Language (not Literature in English) and Mathematics and any three subjects from the following: Economics/Commerce, Business Methods, Principles of Accounts, Literature in English Geography Office Practice Government, Biology/Agricultural Science, Chemistry, Physics, History/Government Typewriting Shorthand",
    utme: "Mathematics, and two of Geography, Commerce, Government, Principles of Accounts, and Economics.",
    years: "2-3",
    degree: "NATIONAL DIPLOMA",
    degreeAbbr: "ND",
    mode: "FT/PT",
    courseSummary: "",
    institutionType: "Polytechnic",
    image: "/accountancy-abiapoly",
  },
  {
    id: 2,
    course: "COMPUTER SOFTWARE ENGINEERING TECHNOLOGY",
    schools: "BUCKINGHAM",
    utme: "Mathematics, Economics, and any of Geography, Commerce, and Principles of Accounts.",
    years: "nil",
    degree: "National Innovation Diploma",
    degreeAbbr: "NID",
    mode: "FT/PT",
    institutionType: "Innovation",
    image: "/computersoftwareengineeringtechnology-buckingham",
  },
  {
    id: 1,
    course: "BUSINESS EDUCATION",
    schools: "AGBOR",
    ssce: "SSCE credit passes or TC II merits in English Language and any three of: 1. Economics 2. Accounts 3. Government 4. Geography 5. History 6. Business Method 7. Statistics 8. Commerce 9. Any Science subjects NB: GROUP A: Commercial Arithmetic Costing, Principles of Accounts, Book Keeping Mathematics, Statistics. GROUP B: Office Practice, Business Method, Commerce, Economics.",
    utme: "Mathematics, Economics, and any of Geography, Commerce, and Principles of Accounts.",
    years: "nil",
    degree: "NIGERIA CERTIFICATE IN EDUCATION",
    degreeAbbr: "NCE",
    mode: "FT/PT",
    institutionType: "College",
    image: "/businesseducation-agbor",
    isFeatured: true,
  },
];
